# Generated by Django 4.2.5 on 2024-03-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
